version: "3.9"

services:
  library:
    image: teamrocket/library-service:1.0
    container_name: library-service
    depends_on:
      - library_postgres
    ports:
      - "8030:8030"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://librarydb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      school:
  librarydb:
    image: postgres:13.1-alpine
    container_name: librarydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      school:

networks:
  school:
    external: true
