version: "3.9"

services:
  studentdb:
    container_name: students-db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      school:
    volumes:
      - db:/var/lib/postgresql
  student:
    container_name: student-service
    image: teamrocket/student-service:1.0
    depends_on:
      - studentdb
    environment:
      STUDENTS_SERVER_PORT: 8888
      STUDENTS_POSTGRES_HOST: studentdb
      STUDENTS_POSTGRES_PORT: 5432
      STUDENTS_POSTGRES_DB: postgres
      STUDENTS_POSTGRES_USERNAME: postgres
      STUDENTS_POSTGRES_PASSWORD: postgres
      STUDENTS_KAFKA_HOST: kafka
      STUDENTS_KAFKA_PORT: 9092
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8888:8888"
    networks:
      school:

volumes:
  db:

networks:
  school:
    external: true